[package]
name = "onnx-runtime-cli"
version = "0.1.0"
edition = "2021"
authors = ["Attilio Oliva", "Aldo Pietromatera", "Andrea Leone"]
license = "MIT"
repository = "https://github.com/ProgrammazioneDiSistema2023-IA-ZZ/Group20"

[dependencies]
onnx-runtime = { path = "../onnx-runtime" }